server:
  port: 9090

netty:
  host: 127.0.0.1
  port: 7379

knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
  basic:
    enable: true
    username: admin
    password: 123456

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER